// <auto-generated />
using LabCourse.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabCourse.Migrations
{
    [DbContext(typeof(ProfesoriDB))]
    partial class ProfesoriDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LabCourse.models.Profesori", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EmriMbiemri")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("departamenti")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("lenda")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Profesoret");
                });
#pragma warning restore 612, 618
        }
    }
}
